import = ["~/.config/alacritty/theme.toml"]

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono NFM"

[window]
decorations = "none"

[cursor]
style = "beam"

[shell]
program = "/usr/bin/zsh"
args = ["-c", "tmux attach || tmux new"]
